#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sudoku.Droid.Resource", IsApplication=true)]

namespace Sudoku.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int barre_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_appi = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_menu = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int c1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int c2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int c3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int c4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int c5 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int c6 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int c7 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int c8 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int c9 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int caseVoid = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int caseVoidR = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int cm1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int cm2 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int cm3 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int cm4 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int cm5 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int cm6 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int cm7 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int cm8 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int cm9 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Icon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int logo = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int logogrand = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060011
			public const int Save = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int Valider = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int b0 = 2131099663;
			
			// aapt resource value: 0x7f060005
			public const int b1 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int b2 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int b3 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int b4 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int b5 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int b6 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int b7 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int b8 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int b9 = 2131099662;
			
			// aapt resource value: 0x7f060015
			public const int buttonHelps = 2131099669;
			
			// aapt resource value: 0x7f060012
			public const int buttonPlay = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int buttonSaved = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int buttonSettings = 2131099668;
			
			// aapt resource value: 0x7f060003
			public const int grille = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout1 = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout2 = 2131099658;
			
			// aapt resource value: 0x7f060016
			public const int switchM = 2131099670;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Help = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LPlay = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Set = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int neigequitombe = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
